<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260807144542 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create game_session table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, period VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, campaign_id INT NOT NULL, calendar_slot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4586AAFBF639F774 ON game_session (campaign_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4586AAFB3B926A5B ON game_session (calendar_slot_id)');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFBF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFB3B926A5B FOREIGN KEY (calendar_slot_id) REFERENCES calendar_slot (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFBF639F774');
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFB3B926A5B');
        $this->addSql('DROP TABLE game_session');
    }
}
