<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260809180946 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, count INT NOT NULL, week_start DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, gm_id INT NOT NULL, campaign_id INT NOT NULL, participant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CABD7C6FBC ON notification (gm_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAF639F774 ON notification (campaign_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA9D1C3019 ON notification (participant_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CABD7C6FBC FOREIGN KEY (gm_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CABD7C6FBC');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAF639F774');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA9D1C3019');
        $this->addSql('DROP TABLE notification');
    }
}
