<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260806193349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(32) NOT NULL, participant_id INT NOT NULL, calendar_slot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3FB7A2BF9D1C3019 ON availability (participant_id)');
        $this->addSql('CREATE INDEX IDX_3FB7A2BF3B926A5B ON availability (calendar_slot_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_availability_participant_slot ON availability (participant_id, calendar_slot_id)');
        $this->addSql('CREATE TABLE calendar_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, period VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, blocked_reason VARCHAR(255) DEFAULT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE98A333F639F774 ON calendar_slot (campaign_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_calendar_slot_campaign_date_period ON calendar_slot (campaign_id, date, period)');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BF9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BF3B926A5B FOREIGN KEY (calendar_slot_id) REFERENCES calendar_slot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_slot ADD CONSTRAINT FK_FE98A333F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE availability DROP CONSTRAINT FK_3FB7A2BF9D1C3019');
        $this->addSql('ALTER TABLE availability DROP CONSTRAINT FK_3FB7A2BF3B926A5B');
        $this->addSql('ALTER TABLE calendar_slot DROP CONSTRAINT FK_FE98A333F639F774');
        $this->addSql('DROP TABLE availability');
        $this->addSql('DROP TABLE calendar_slot');
    }
}
